=== Liturgical-Calendar/LiturgicalCalendar/jsondata/schemas/Index.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
            "calendar_id": {
                "$ref": "https://litcal.johnromanodorazio.com/api/dev/schemas/CommonDef.json#/definitions/DiocesanCalendarId"
            },
            "path": {
                "type": "string",
                "pattern": "^jsondata\\\/sourcedata\\\/nations\\\/[A-Z]{2}\\\/[a-zA-Z0-9 ()'-]+\\.json$"
            },
            "nation": {
                "$ref": "https://litcal.johnromanodorazio.com/api/dev/schemas/CommonDef.json#/definitions/Region"
            },
            "diocese": {
                "type": "string",
                "pattern": "^[a-zA-Z0-9 ()'-]+$"
            },
            "group": {
                "type": "string"
            }
        },
        "required": [
            "calendar_id",
            "path",
            "nation",
            "diocese"
        ]
    }
}

=== Liturgical-Calendar/LiturgicalCalendar/jsondata/sourcedata/calendars/dioceses/index.json
[
    {
        "calendar_id": "romamo_it",
        "path": "jsondata\/sourcedata\/calendars\/dioceses\/IT\/romamo_it\/Diocesi di Roma.json",
        "nation": "IT",
        "diocese": "Diocesi di Roma",
        "group": "Diocesi del Lazio"
    },
    {
        "calendar_id": "boston_us",
        "path": "jsondata\/sourcedata\/calendars\/dioceses\/US\/boston_us\/Archdiocese of Boston (Massachusetts).json",
        "nation": "US",
        "diocese": "Archdiocese of Boston (Massachusetts)"
    },
    {
        "calendar_id": "socaap_it",
        "path": "jsondata\/sourcedata\/calendars\/dioceses\/IT\/socaap_it\/Diocesi di Sora - Cassino - Aquino - Pontecorvo.json",
        "nation": "IT",
        "diocese": "Diocesi di Sora - Cassino - Aquino - Pontecorvo",
        "group": "Diocesi del Lazio"
    },
    {
        "calendar_id": "roermo_nl",
        "path": "jsondata\/sourcedata\/calendars\/dioceses\/NL\/roermo_nl\/Roermond.json",
        "nation": "NL",
        "diocese": "Roermond"
    },
    {
        "calendar_id": "sherto_nl",
        "path": "jsondata\/sourcedata\/calendars\/dioceses\/NL\/sherto_nl\/'s-Hertogenbosch.json",
        "nation": "NL",
        "diocese": "'s-Hertogenbosch"
    },
    {
        "calendar_id": "utrech_nl",
        "path": "jsondata\/sourcedata\/calendars\/dioceses\/NL\/utrech_nl\/Utrecht.json",
        "nation": "NL",
        "diocese": "Utrecht"
    },
    {
        "calendar_id": "rotter_nl",
        "path": "jsondata\/sourcedata\/calendars\/dioceses\/NL\/rotter_nl\/Rotterdam.json",
        "nation": "NL",
        "diocese": "Rotterdam"
    },
    {
        "calendar_id": "grolee_nl",
        "path": "jsondata\/sourcedata\/calendars\/dioceses\/NL\/grolee_nl\/Groningen-Leeuwarden.json",
        "nation": "NL",
        "diocese": "Groningen-Leeuwarden"
    },
    {
        "calendar_id": "bredad_nl",
        "path": "jsondata\/sourcedata\/calendars\/dioceses\/NL\/bredad_nl\/Breda.json",
        "nation": "NL",
        "diocese": "Breda"
    },
    {
        "calendar_id": "haaams_nl",
        "path": "jsondata\/sourcedata\/calendars\/dioceses\/NL\/haaams_nl\/Haarlem-Amsterdam.json",
        "nation": "NL",
        "diocese": "Haarlem-Amsterdam"
    }
]

=== Liturgical-Calendar/LiturgicalCalendar/jsondata/sourcedata/nations/index.json
[
    {
        "calendar_id": "romamo_it",
        "path": "jsondata\/sourcedata\/nations\/IT\/Diocesi di Roma.json",
        "nation": "IT",
        "diocese": "Diocesi di Roma",
        "group": "Diocesi del Lazio"
    },
    {
        "calendar_id": "boston_us",
        "path": "jsondata\/sourcedata\/nations\/US\/Archdiocese of Boston (Massachusetts).json",
        "nation": "US",
        "diocese": "Archdiocese of Boston (Massachusetts)"
    },
    {
        "calendar_id": "socaap_it",
        "path": "jsondata\/sourcedata\/nations\/IT\/Diocesi di Sora - Cassino - Aquino - Pontecorvo.json",
        "nation": "IT",
        "diocese": "Diocesi di Sora - Cassino - Aquino - Pontecorvo",
        "group": "Diocesi del Lazio"
    },
    {
        "calendar_id": "roermo_nl",
        "path": "jsondata\/sourcedata\/nations\/NL\/Roermond.json",
        "nation": "NL",
        "diocese": "Roermond"
    },
    {
        "calendar_id": "sherto_nl",
        "path": "jsondata\/sourcedata\/nations\/NL\/'s-Hertogenbosch.json",
        "nation": "NL",
        "diocese": "'s-Hertogenbosch"
    },
    {
        "calendar_id": "utrech_nl",
        "path": "jsondata\/sourcedata\/nations\/NL\/Utrecht.json",
        "nation": "NL",
        "diocese": "Utrecht"
    },
    {
        "calendar_id": "rotter_nl",
        "path": "jsondata\/sourcedata\/nations\/NL\/Rotterdam.json",
        "nation": "NL",
        "diocese": "Rotterdam"
    },
    {
        "calendar_id": "grolee_nl",
        "path": "jsondata\/sourcedata\/nations\/NL\/Groningen-Leeuwarden.json",
        "nation": "NL",
        "diocese": "Groningen-Leeuwarden"
    },
    {
        "calendar_id": "bredad_nl",
        "path": "jsondata\/sourcedata\/nations\/NL\/Breda.json",
        "nation": "NL",
        "diocese": "Breda"
    },
    {
        "calendar_id": "haaams_nl",
        "path": "jsondata\/sourcedata\/nations\/NL\/Haarlem-Amsterdam.json",
        "nation": "NL",
        "diocese": "Haarlem-Amsterdam"
    }
]
