=== Liturgical-Calendar/LiturgicalCalendar/schemas/LitCalTests.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/LitCalTests",
    "definitions": {
        "LitCalTests": {
            "type": "object",
            "properties": {
                "name" : {
                    "type": "string",
                    "pattern": "[A-Z][a-zA-Z]*Test$"
                },
                "eventkey": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "testType": {
                    "type": "string",
                    "enum": [
                        "exactCorrespondence",
                        "exactCorrespondenceSince",
                        "variableCorrespondence"
                    ]
                },
                "appliesTo": {
                    "$ref": "#/definitions/AppliesToOrExcludes"
                },
                "excludes": {
                    "$ref": "#/definitions/AppliesToOrExcludes"
                },
                "assertions": {
                    "type": "array",
                    "items": {
                        "anyOf": [
                            {
                                "type": "object",
                                "properties": {
                                    "year": {
                                        "$ref": "#/definitions/Year"
                                    },
                                    "expectedValue": {
                                        "type": "null"
                                    },
                                    "assert": {
                                        "type": "string",
                                        "enum": [
                                            "eventNotExists"
                                        ]
                                    },
                                    "assertion": {
                                        "type": "string"
                                    }
                                },
                                "required": [ "year", "expectedValue", "assert", "assertion" ]
                            },
                            {
                                "type": "object",
                                "properties": {
                                    "year": {
                                        "$ref": "#/definitions/Year"
                                    },
                                    "expectedValue": {
                                        "type": "integer",
                                        "minimum": -2851200,
                                        "maximum": 253402214400
                                    },
                                    "assert": {
                                        "type": "string",
                                        "enum": [
                                            "eventExists AND hasExpectedTimestamp"
                                        ]
                                    },
                                    "assertion": {
                                        "type": "string"
                                    }
                                },
                                "required": [ "year", "expectedValue", "assert", "assertion" ]
                            }
                        ]
                    }
                }
            },
            "required": [ "name", "eventkey", "description", "testType", "assertions" ]
        },
        "AppliesToOrExcludes": {
            "type": "object",
            "minProperties": 1,
            "properties": {
                "nationalcalendar": {
                    "type": "string"
                },
                "diocesancalendar": {
                    "type": "string"
                },
                "nationalcalendars": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "diocesancalendars": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "anyOf": [
                { "required": ["nationalcalendar"] },
                { "required": ["nationalcalendars"] },
                { "required": ["diocesancalendar"] },
                { "required": ["diocesancalendars"] }
            ]
        },
        "Year": {
            "type": "integer",
            "minimum": 1970,
            "maximum": 9999
        }
    }
}

=== Liturgical-Calendar/LiturgicalCalendar/tests/StJaneFrancesDeChantalTest.json
{
    "name": "StJaneFrancesDeChantalTest",
    "eventkey": "StJaneFrancesDeChantal",
    "description": "Saint Jane Frances de Chantal was moved from December 12 to August 12 in the 2002 Latin Edition of the Roman Missal, to allow bishops conferences to insert Our Lady of Guadalupe as an optional memorial on December 12. DOES ST JANE FRANCES DE CHANTAL FALL ON THE RIGHT DAY BOTH BEFORE AND AFTER 2002, OR IT CORRECTLY OVERRIDEN BY GREATER FESTIVITIES?",
    "testType": "variableCorrespondence",
    "assertions": [
        {
            "year": 2001,
            "expectedValue": 1008115200,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "should fall on expected date December 12"
        },
        {
            "year": 2002,
            "expectedValue": 1029110400,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "should fall on expected date August 12"
        },
        {
            "year": 2010,
            "expectedValue": 1281571200,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "should fall on expected date August 12",
            "comment": "this test is significant since December 12th falls on a Sunday, so the memorial would have been suppressed if it hadn't been moved"
        },
        {
            "year": 1971,
            "expectedValue": null,
            "assert": "eventNotExists",
            "assertion": "should not exist, December 12th is a Sunday"
        },
        {
            "year": 1976,
            "expectedValue": null,
            "assert": "eventNotExists",
            "assertion": "should not exist, December 12th is a Sunday"
        },
        {
            "year": 1982,
            "expectedValue": null,
            "assert": "eventNotExists",
            "assertion": "should not exist, December 12th is a Sunday"
        },
        {
            "year": 1993,
            "expectedValue": null,
            "assert": "eventNotExists",
            "assertion": "should not exist, December 12th is a Sunday"
        },
        {
            "year": 1999,
            "expectedValue": null,
            "assert": "eventNotExists",
            "assertion": "should not exist, December 12th is a Sunday"
        },
        {
            "year": 2012,
            "expectedValue": null,
            "assert": "eventNotExists",
            "assertion": "should not exist, December 12th is a Sunday"
        },
        {
            "year": 2018,
            "expectedValue": null,
            "assert": "eventNotExists",
            "assertion": "should not exist, December 12th is a Sunday"
        },
        {
            "year": 2029,
            "expectedValue": null,
            "assert": "eventNotExists",
            "assertion": "should not exist, December 12th is a Sunday"
        },
        {
            "year": 2035,
            "expectedValue": null,
            "assert": "eventNotExists",
            "assertion": "should not exist, December 12th is a Sunday"
        },
        {
            "year": 2040,
            "expectedValue": null,
            "assert": "eventNotExists",
            "assertion": "should not exist, December 12th is a Sunday"
        },
        {
            "year": 2046,
            "expectedValue": null,
            "assert": "eventNotExists",
            "assertion": "should not exist, December 12th is a Sunday"
        }
    ]
}

=== Liturgical-Calendar/LiturgicalCalendar/tests/ROTTERDAM_HLaurentiusdiakenenmartelaarpatroonvanhetbisdomTest.json
{
    "name": "ROTTERDAM_HLaurentiusdiakenenmartelaarpatroonvanhetbisdomTest",
    "testType": "exactCorrespondence",
    "description": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10",
    "assertions": [
        {
            "year": 1999,
            "expectedValue": 934243200,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2000,
            "expectedValue": 965865600,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2001,
            "expectedValue": 997401600,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2002,
            "expectedValue": 1028937600,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2003,
            "expectedValue": 1060560000,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 11",
            "comment": "since this is a Sunday, the feast should have been moved to the next day"
        },
        {
            "year": 2004,
            "expectedValue": 1092096000,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2005,
            "expectedValue": 1123632000,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2006,
            "expectedValue": 1155168000,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2007,
            "expectedValue": 1186704000,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2008,
            "expectedValue": 1218412800,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 11",
            "comment": "since this is a Sunday, the feast should have been moved to the next day"
        },
        {
            "year": 2009,
            "expectedValue": 1249862400,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2010,
            "expectedValue": 1281398400,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2011,
            "expectedValue": 1312934400,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2012,
            "expectedValue": 1344556800,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2013,
            "expectedValue": 1376092800,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2014,
            "expectedValue": 1407715200,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 11",
            "comment": "since this is a Sunday, the feast should have been moved to the next day"
        },
        {
            "year": 2015,
            "expectedValue": 1439164800,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2016,
            "expectedValue": 1470787200,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2017,
            "expectedValue": 1502323200,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2018,
            "expectedValue": 1533859200,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2019,
            "expectedValue": 1565395200,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2020,
            "expectedValue": 1597017600,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2021,
            "expectedValue": 1628553600,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2022,
            "expectedValue": 1660089600,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2023,
            "expectedValue": 1691625600,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2024,
            "expectedValue": 1723248000,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2025,
            "expectedValue": 1754870400,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 11",
            "comment": "since this is a Sunday, the feast should have been moved to the next day"
        },
        {
            "year": 2026,
            "expectedValue": 1786320000,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2027,
            "expectedValue": 1817856000,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2028,
            "expectedValue": 1849478400,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2029,
            "expectedValue": 1881014400,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        },
        {
            "year": 2030,
            "expectedValue": 1912550400,
            "assert": "eventExists AND hasExpectedTimestamp",
            "assertion": "The FEAST of &#039;H. Laurentius, diaken en martelaar, patroon van het bisdom&#039; should fall on August 10"
        }
    ],
    "eventkey": "ROTTERDAM_HLaurentiusdiakenenmartelaarpatroonvanhetbisdom",
    "appliesTo": {
        "diocesancalendar": "ROTTERDAM"
    }
}
